/*CREATE TABLE PERSON1(
id int not null primary key AUTO_INCREMENT,
name varchar(255),
location varchar(255),
birth_date timestamp,
created_date timestamp,
lastUpdate_date timestamp
);*/

/*INSERT INTO PERSON1(id,name,location,birth_date,created_date,lastUpdate_date) 
VALUES (1,'Revanth','Shayampet','1997-10-13','1997-10-13','1997-10-13');
INSERT INTO PERSON1(id,name,location,birth_date,created_date,lastUpdate_date) 
VALUES (2,'Dembele','Rennes','1997-05-15','1997-10-13','1997-10-13');
INSERT INTO PERSON1(id,name,location,birth_date,created_date,lastUpdate_date) 
VALUES (3,'Reus','Dortmund','1992-05-20','1997-10-13','1997-10-13');*/
/*create table course (
        id integer generated by default as identity,
        created_date timestamp(6),
        last_update_date timestamp(6),
        name varchar(255),
        primary key (id)
    );
create table passport (
        id bigint generated by default as identity,
        number varchar(255),
        primary key (id)
    );*/
/*INSERT INTO Passport(id,number)
VALUES(1,'E12345');
INSERT INTO Passport(id,number)
VALUES(2,'E12346');
INSERT INTO Passport(id,number)
VALUES(3,'E12347');

INSERT INTO Student(id,name,passport_id)
VALUES(1,'Sachin',1);
INSERT INTO Student(id,name,passport_id)
VALUES(2,'Sehwag',2);
INSERT INTO Student(id,name,passport_id)
VALUES(3,'Yuvraj',3);*/